name: C++ CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake g++

      - name: Create build directory
        run: mkdir -p build

      - name: Configure CMake
        run: cmake -B build

      - name: Build project
        run: cmake --build build

      - name: Run executable (Unix)
        run: ./build/operating_system_lab
        if: runner.os != 'Windows'

      - name: Run executable (Windows)
        run: build\\operating_system_lab.exe
        if: runner.os == 'Windows'

      - name: Clean up build files
        run: cmake --build build --target clean
